# Generated by Django 3.2.18 on 2023-03-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0002_auto_20230307_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
