# Generated by Django 3.2.18 on 2023-03-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0005_auto_20230308_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit_recipe',
            name='status',
        ),
    ]
