# Generated by Django 3.2.18 on 2023-03-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0006_remove_submit_recipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
