# Generated by Django 3.2.18 on 2023-05-19 16:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0009_alter_submit_recipe_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='description')),
                ('ingredients', models.TextField(default='ingredients')),
                ('instructions', models.TextField(default='instructions')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ingredients_field',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='instructions_field',
            new_name='instructions',
        ),
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.CharField(default='', max_length=100),
        ),
    ]
