# Generated by Django 3.2.18 on 2023-05-24 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipesite', '0010_auto_20230519_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submit_Recipe',
            new_name='Submission',
        ),
    ]
