# Generated by Django 3.2.18 on 2023-06-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0014_auto_20230526_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
