# Generated by Django 3.2.18 on 2023-06-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0015_alter_memberrecipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrecipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
