# Generated by Django 3.2.18 on 2023-06-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0016_alter_memberrecipe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='author',
        ),
    ]
