# Generated by Django 3.2.18 on 2023-06-08 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipesite', '0017_remove_submission_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberrecipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberrecipe',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
    ]
