# Generated by Django 3.2.18 on 2023-06-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0020_alter_memberrecipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberrecipe',
            name='user',
        ),
    ]
