# Generated by Django 3.2.18 on 2023-06-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0021_remove_memberrecipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberrecipe',
            name='published',
        ),
    ]
