# Generated by Django 3.2.18 on 2023-06-09 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipesite', '0022_remove_memberrecipe_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='memberrecipe_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
