# Generated by Django 3.2.18 on 2023-06-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0026_recipe_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
