# Generated by Django 3.2.18 on 2023-06-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0028_submission_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
