# Generated by Django 3.2.18 on 2023-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0030_membersrecipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersrecipes',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='membersrecipes',
            name='publish_recipes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
