# Generated by Django 3.2.18 on 2023-06-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0032_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_on']},
        ),
        migrations.DeleteModel(
            name='MembersRecipes',
        ),
    ]
