# Generated by Django 3.2.18 on 2023-06-15 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipesite', '0033_auto_20230615_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memberrecipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
