# Generated by Django 3.2.18 on 2023-06-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0034_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='author',
            new_name='name',
        ),
    ]
