# Generated by Django 3.2.18 on 2023-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0034_submission_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='published',
        ),
        migrations.AddField(
            model_name='submission',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
