# Generated by Django 3.2.18 on 2023-06-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0035_auto_20230616_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
