# Generated by Django 3.2.18 on 2023-06-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0035_rename_author_submission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='name',
        ),
    ]
