# Generated by Django 3.2.18 on 2023-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0036_alter_submission_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='published',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
