# Generated by Django 3.2.18 on 2023-06-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0036_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
