# Generated by Django 3.2.18 on 2023-06-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0038_alter_submission_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Submissions'},
        ),
    ]
