# Generated by Django 3.2.18 on 2023-06-17 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipesite', '0040_rename_author_submission_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
