# Generated by Django 3.2.18 on 2023-06-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0041_submission_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
