# Generated by Django 3.2.18 on 2023-07-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0042_alter_submission_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recipe',
            new_name='title',
        ),
    ]
