# Generated by Django 3.2.18 on 2023-07-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0043_rename_recipe_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
