# Generated by Django 3.2.18 on 2023-07-07 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipesite', '0044_rename_is_approved_recipe_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='submission_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
