# Generated by Django 3.2.18 on 2023-07-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0045_alter_submission_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipesite.recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipesite.submission'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(default='no title', max_length=200),
        ),
    ]
