# Generated by Django 3.2.18 on 2023-07-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0048_auto_20230712_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipesite.submission'),
        ),
    ]
