# Generated by Django 3.2.18 on 2023-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0052_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submissions',
            field=models.ManyToManyField(to='recipesite.Submission'),
        ),
    ]
