# Generated by Django 3.2.18 on 2023-07-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0052_auto_20230717_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
